# Generated by Django 3.2.6 on 2021-08-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210817_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sexe',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Femele')], max_length=10),
        ),
    ]
