# Generated by Django 3.2.6 on 2021-08-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_account_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='lastname',
            field=models.CharField(max_length=150),
        ),
    ]
