# Generated by Django 3.2.6 on 2021-08-18 13:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_coachrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachrating',
            name='stars',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='coachrating',
            name='coach',
            field=models.ForeignKey(limit_choices_to={'user_type': 1}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Coach', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='coachrating',
            unique_together={('account', 'coach')},
        ),
        migrations.AlterIndexTogether(
            name='coachrating',
            index_together={('account', 'coach')},
        ),
    ]
