# Generated by Django 3.2.6 on 2021-08-18 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210818_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachrating',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
