# Generated by Django 3.2.6 on 2021-08-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
