# Generated by Django 3.2.6 on 2021-08-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_blog_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.BooleanField(),
        ),
    ]
