# Generated by Django 3.2.6 on 2021-08-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_blograting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blograting',
            options={'ordering': ['-rating_date']},
        ),
        migrations.AddField(
            model_name='blog',
            name='source',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
