# Generated by Django 3.2.6 on 2021-08-19 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_blogcomments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogComments',
            new_name='BlogComment',
        ),
    ]
