# Generated by Django 3.2.6 on 2021-08-19 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_blogcomments_blogcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessProgramsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=1000)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('fitprog', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.fitnessprogram')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
