# Generated by Django 3.2.6 on 2021-08-19 21:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_account_startdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('about', models.TextField(max_length=7000)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('duration', models.IntegerField()),
                ('day_per_week', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('difficulty', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('body_focus', models.CharField(max_length=500)),
                ('equipments', models.CharField(blank=True, max_length=500)),
                ('training_type', models.CharField(max_length=800)),
                ('workout_type', models.CharField(choices=[('C', 'Challenge'), ('P', 'Program')], default=('C', 'Challenge'), max_length=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('fitprog', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.fitnessprogram')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
