# Generated by Django 3.2.6 on 2021-08-19 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_workout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='duration',
            new_name='mb_of_weeks',
        ),
    ]
