# Generated by Django 3.2.6 on 2021-08-19 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_duration_workout_mb_of_weeks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='name',
            new_name='title',
        ),
    ]
