# Generated by Django 3.2.6 on 2021-08-19 23:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_mb_of_weeks_workout_nb_of_weeks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blograting',
            name='rating_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='coachrating',
            name='rating_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='doctorrating',
            name='rating_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fitnessprogramsrating',
            name='rating_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usersfitnessprograms',
            name='joined_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='WorkoutsRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_date', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.workout')),
            ],
            options={
                'ordering': ['-rating_date'],
                'unique_together': {('account', 'workout')},
                'index_together': {('account', 'workout')},
            },
        ),
    ]
