# Generated by Django 3.2.6 on 2021-08-22 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_account_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coachrating',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coachrating',
            name='coach',
            field=models.ForeignKey(limit_choices_to={'user_type': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='Coach', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorrating',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorrating',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'user_type': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='Doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fitnessprogramscomment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fitnessprogramscomment',
            name='fitprog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fitnessprogram'),
        ),
        migrations.AlterField(
            model_name='fitnessprogramsrating',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fitnessprogramsrating',
            name='fitprog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fitnessprogram'),
        ),
        migrations.AlterField(
            model_name='usersfitnessprograms',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersfitnessprograms',
            name='fitprog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fitnessprogram'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workout',
            name='fitprog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fitnessprogram'),
        ),
        migrations.AlterField(
            model_name='workoutcomment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutsrating',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
