# Generated by Django 3.2.6 on 2021-10-24 21:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20210822_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_date', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('account_to_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_to_rate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('account', 'account_to_rate')},
                'index_together': {('account', 'account_to_rate')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='doctorrating',
            unique_together=None,
        ),
        migrations.AlterIndexTogether(
            name='doctorrating',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='doctorrating',
            name='account',
        ),
        migrations.RemoveField(
            model_name='doctorrating',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='CoachRating',
        ),
        migrations.DeleteModel(
            name='DoctorRating',
        ),
    ]
